### ISSUE TITLE
Make color editable

### ISSUE THREAD

**Issue by nielslange** [woocommerce/woocommerce-free-shipping-progress-bar-block#6]
To allow merchants to apply their style guide to the plugin, the merchants should be able to adjust the colors. 

## Used colors 
- ~Font color~
- ~Background color of outer progress bar~
- ~Background color of inner progress bar~
- ~Border color of outer progress bar~
- Message color
- Progress bar color

**Comment by senadir** [comment]
Might need to run this issue with Viv and Gary fist. Having 4 color switcher might be too much. I'm thinking mostly two, the text (which would be shared with the progress bar, and the border of the progress bar) and the background.

**Comment by nielslange** [comment]
> Might need to run this issue with Viv and Gary fist. Having 4 color switcher might be too much. I'm thinking mostly two, the text (which would be shared with the progress bar, and the border of the progress bar) and the background.

Yes, that make sense. I implement two color selectors for now and will run the design by Vivien and Gary later on once I have a working prototype.
